[general]
import = [
  "~/Documents/dotfiles/alacritty/catppuccin-macchiato.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

